---
title: "DATATHON"
author: "ROBERT"
format: pdf
editor: visual
---

```{r}
libr <- c("googlesheets4","tidytext","tidyr","ggplot2", "forcats","tidyverse")
lapply(libr, library, character.only = TRUE)
```




```{r}
#install.packages("googlesheets4")
library(googlesheets4)
# Authenticate with your Google account (you'll be prompted to log in)
gs4_auth()

# Provide the Google Sheets link to the specific sheet you want to access
sheet_link <- "https://docs.google.com/spreadsheets/d/1YHuxiQKQmI23UcseEEYL-B7cXD6v6vtVr8iA6wKf3lg/edit#gid=1422694223"

# Read the "Malaria-studies" sheet as a data frame
pneumonia <- read_sheet(sheet_link, sheet = "Pneumonia-studies")
head(pneumonia)
sum(is.na(pneumonia))
colnames(pneumonia)
```


```{r}
pneumonia.clean <-  pneumonia %>%
  select(-`Study Title`,-`Brief Summary`,-`Primary Outcome Measures`,-`NCT Number`,-`Study URL`,-`Secondary Outcome Measures`,-`Other Outcome Measures`, -`Start Date`, -`Primary Completion Date`, - `Completion Date`, -`First Posted`, -`Last Update Posted`,-Conditions,-Interventions,-Sponsor,-Collaborators,-`Study Design`,-`Other IDs`,-Locations,-`Study Documents`,-Acronym,-`Results First Posted`) %>%
  mutate(duration = as.numeric(sub(" secs","", (pneumonia$`Completion Date` - pneumonia$`Start Date`)/86400))) #duration of study

```




```{r}
pneumonia.clean$`Study Status` <- fct_recode(pneumonia.clean$`Study Status`, "1" = "UNKNOWN",
  "2" = "TERMINATED",
  "3" = "COMPLETED",
  "4" = "ACTIVE_NOT_RECRUITING",
  "5" = "WITHDRAWN",
  "6" = "NOT_YET_RECRUITING",
  "7" = "RECRUITING",
  "8" = "NO_LONGER_AVAILABLE",
  "9" = "ENROLLING_BY_INVITATION",
  "10" = "SUSPENDED",
  "11" = "AVAILABLE",
  "12" = "APPROVED_FOR_MARKETING")

pneumonia.clean$`Study Results` <- fct_recode(pneumonia.clean$`Study Results`,
  "1" = "NO",
  "2" = "YES"
)

pneumonia.clean$Sex <-  fct_recode(pneumonia.clean$Sex,
  "1" = "ALL",
  "2" = "FEMALE",
  "3" = "MALE",
  "4" = "NA"
)

pneumonia.clean$Age <-  fct_recode(
  pneumonia.clean$Age,
  "1" = "CHILD",
  "2" = "ADULT, OLDER_ADULT",
  "3" = "ADULT",
  "4" = "CHILD, ADULT, OLDER_ADULT",
  "5" = "CHILD, ADULT",
  "6" = "OLDER_ADULT"
)

 # Recode the levels into numeric values
pneumonia.clean$Phases <- fct_recode(
  pneumonia.clean$Phases,
  "1" = "NA",
  "2" = "PHASE4",
   "3" = "<NA>",
  "4" = "PHASE2",
  "5" = "EARLY_PHASE1",
  "6" = "PHASE1",
  "7" = "PHASE3",
  "8" = "PHASE2|PHASE3",
  "9" = "PHASE1|PHASE2"
)

pneumonia.clean$`Funder Type` <- fct_recode(pneumonia.clean$`Funder Type`,
  "1" = "OTHER_GOV",
  "2" = "OTHER",
  "3" = "INDUSTRY",
  "4" = "NETWORK",
  "5" = "NIH",
  "6" = "FED",
  "7" = "INDIV",
  "8" = "UNKNOWN"
)
 
pneumonia.clean$`Study Type` <-   fct_recode(pneumonia.clean$`Study Type`,
  "1" = "INTERVENTIONAL",
  "2" = "OBSERVATIONAL",
  "3" = "EXPANDED_ACCESS"
)
(pneumonia.clean)
pneumonia.clean <-  na.omit(pneumonia.clean)
```

#   visualisation

```{r}
pneumonia.clean %>%
  ggplot(mapping = aes(x = `Funder Type`, y = Enrollment, fill = `Funder Type`)) +
  geom_col()

pneumonia.clean %>%
  ggplot(mapping = aes(x = Enrollment, y = Age, fill = Phases))+
  geom_col() + 
  coord_flip()

pneumonia.clean %>%
  ggplot(mapping = aes(x = Enrollment, y = `Study Results`))+
  geom_col() + 
  coord_flip()
```



```{r}
pneumonia.clean %>%
  ggplot(mapping = aes(x = Enrollment, y = `Study Status`))+
  geom_col() + 
  coord_flip()
```


##    CLASSIFICATION

```{r}

```

